drop table IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

drop table IF EXISTS items CASCADE;
CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) not null,
    description VARCHAR(512) not null,
    available   BOOLEAN      not null,
    owner       LONG         not null,
    constraint items_pk
        primary key (id),
    constraint "items_USERS_id_fk"
        foreign key (owner) references users (id)
);

CREATE TYPE IF NOT EXISTS status as ENUM('WAITING', 'APPROVED', 'REJECTED', 'CANCELED');


CREATE TABLE IF NOT EXISTS booking
(
    ID            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    START_BOOKING TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    END_BOOKING   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    ITEM_ID       BIGINT not null,
    USER_ID       BIGINT not null,
    BOOKING_STATUS PUBLIC.STATUS,
    constraint "BOOKING_pk"
        primary key (ID),
    constraint "BOOKING_ITEMS_ID_fk"
        foreign key (ITEM_ID) references ITEMS (id),
    constraint BOOKING_USERS_ID_FK
        foreign key (USER_ID) references USERS (id)
);

