--drop table IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

--drop table IF EXISTS item_request CASCADE;
create table ITEM_REQUEST
(
    REQUEST_ID  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DESCRIPTION CHARACTER VARYING(255) not null,
    REQUESTOR   BIGINT                 not null,
    CREATED     TIMESTAMP              not null,
    constraint PK_ITEM_REQUEST
        primary key (REQUEST_ID),
    constraint ITEM_REQUEST_USERS_USER_ID_FK
        foreign key (REQUESTOR) references USERS
);

--drop table IF EXISTS items CASCADE;
CREATE TABLE IF NOT EXISTS items
(
    ITEM_ID     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ITEM_NAME   CHARACTER VARYING(255) not null,
    DESCRIPTION CHARACTER VARYING(512) not null,
    AVAILABLE   BOOLEAN                not null,
    OWNER       BIGINT                 not null,
    REQUEST     BIGINT,
    constraint ITEMS_PK
        primary key (ITEM_ID),
    constraint FK_ITEM_ITEM_REQUEST
        foreign key (REQUEST) references ITEM_REQUEST
            on delete cascade,
    constraint "items_USERS_id_fk"
        foreign key (OWNER) references USERS
            on delete cascade
);

--drop table IF EXISTS BOOKINGS CASCADE;
CREATE TABLE IF NOT EXISTS bookings
(
    ID             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    START_BOOKING  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    END_BOOKING    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    ITEM_ID        BIGINT                                  not null,
    BOOKER_ID      BIGINT                                  not null,
    BOOKING_STATUS VARCHAR(64) NOT NULL,
    constraint bookings_pk
        primary key (ID),
    constraint "BOOKINGS_ITEMS_ID_fk"
        foreign key (ITEM_ID) references ITEMS (item_id),
    constraint BOOKINGS_USERS_ID_FK
        foreign key (BOOKER_ID) references USERS (user_id)
);

--drop table IF EXISTS COMMENTS CASCADE;
create table COMMENTS
(
    COMMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    TEXT       CHARACTER VARYING(255) not null,
    ITEM_ID    BIGINT                 not null,
    AUTHOR_ID  BIGINT                 not null,
    CREATED    TIMESTAMP              not null,
    constraint COMMENTS_PK
        primary key (COMMENT_ID)
);
